# Generated by Django 6.0.6 on 2026-06-19 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo', models.CharField(blank=True, max_length=500)),
                ('github_token', models.TextField(blank=True)),
                ('jenkins_url', models.CharField(blank=True, max_length=500)),
                ('jenkins_username', models.CharField(blank=True, max_length=255)),
                ('jenkins_token', models.TextField(blank=True)),
                ('aws_access_key', models.TextField(blank=True)),
                ('aws_secret_key', models.TextField(blank=True)),
                ('aws_region', models.CharField(blank=True, max_length=100)),
                ('kubeconfig_file', models.FileField(blank=True, null=True, upload_to='kubeconfigs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='projects.project')),
            ],
        ),
    ]
