#Global Constants

#USER STATUS
USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_INACTIVE = "INACTIVE"
USER_STATUS_BLOCKED = "BLOCKED"
USER_STATUS_CHOICES = (
    (USER_STATUS_ACTIVE, USER_STATUS_ACTIVE),
    (USER_STATUS_INACTIVE, USER_STATUS_INACTIVE),
    (USER_STATUS_BLOCKED, USER_STATUS_BLOCKED),
)

#RESPONSE MESSAGES
SUCCESS = "SUCCESS"
FAILED = "FAILED"

#HTTP MESSAGES
INVALID_CREDENTIALS = "Invalid email or password"
USER_NOT_FOUND = "User not found"
UNAUTHORIZED = "Unauthorized"

#TOKEN TYPES
ACCESS_TOKEN = "ACCESS"
REFRESH_TOKEN = "REFRESH"

#PROJECT STATUS
PROJECT_ACTIVE = "ACTIVE"
PROJECT_ARCHIVED = "ARCHIVED"

# BUILD STATUS
BUILD_STATUS_SUCCESS = "SUCCESS"
BUILD_STATUS_FAILED = "FAILED"
BUILD_STATUS_RUNNING = "RUNNING"
BUILD_STATUS_CHOICES = (
    (BUILD_STATUS_SUCCESS, BUILD_STATUS_SUCCESS),
    (BUILD_STATUS_FAILED, BUILD_STATUS_FAILED),
    (BUILD_STATUS_RUNNING, BUILD_STATUS_RUNNING),
)

# INCIDENT STATUS
INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_RESOLVED = "RESOLVED"
INCIDENT_STATUS_CHOICES = (
    (INCIDENT_STATUS_OPEN, INCIDENT_STATUS_OPEN),
    (INCIDENT_STATUS_RESOLVED, INCIDENT_STATUS_RESOLVED),
)

# ATTEMPT RESULTS
ATTEMPT_RESULT_FAILED = "FAILED"
ATTEMPT_RESULT_SUCCESS = "SUCCESS"
ATTEMPT_RESULT_CHOICES = (
    (ATTEMPT_RESULT_FAILED, ATTEMPT_RESULT_FAILED),
    (ATTEMPT_RESULT_SUCCESS, ATTEMPT_RESULT_SUCCESS),
)