#Global Constants

#USER STATUS
USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_INACTIVE = "INACTIVE"
USER_STATUS_BLOCKED = "BLOCKED"
USER_STATUS_CHOICES = (
    (USER_STATUS_ACTIVE, USER_STATUS_ACTIVE),
    (USER_STATUS_INACTIVE, USER_STATUS_INACTIVE),
    (USER_STATUS_BLOCKED, USER_STATUS_BLOCKED),
)

#RESPONSE MESSAGES
SUCCESS = "SUCCESS"
FAILED = "FAILED"

#HTTP MESSAGES
INVALID_CREDENTIALS = "Invalid email or password"
USER_NOT_FOUND = "User not found"
UNAUTHORIZED = "Unauthorized"

#TOKEN TYPES
ACCESS_TOKEN = "ACCESS"
REFRESH_TOKEN = "REFRESH"

#PROJECT STATUS
PROJECT_ACTIVE = "ACTIVE"
PROJECT_ARCHIVED = "ARCHIVED"

#BUILD STATUS
BUILD_SUCCESS = "SUCCESS"
BUILD_FAILED = "FAILED"
BUILD_RUNNING = "RUNNING"

#INCIDENT STATUS
INCIDENT_OPEN = "OPEN"
INCIDENT_RESOLVED = "RESOLVED"